import React from 'react'
import { useState } from 'react'
import Header from './components/Header'
import Grid from './components/Grid'

function App() {
  const [cells, setCells] = useState([
    [
      { marker: '4', letter: 'y', reminder: true, },
      { marker: '5', letter: 'x', reminder: true, },
      { marker: '8', letter: 't', reminder: false, },
      { marker: '8', letter: 't', reminder: false, },
      { marker: '8', letter: 't', reminder: false, },
      { marker: '8', letter: 't', reminder: false, },
      { marker: '8', letter: 't', reminder: false, },
      { marker: '8', letter: 't', reminder: false, },
      { marker: '8', letter: 't', reminder: false, },
      { marker: '8', letter: 't', reminder: false, },
      { marker: '8', letter: 't', reminder: false, },
      { marker: '8', letter: 't', reminder: false, },
      { marker: '8', letter: 't', reminder: false, },
      { marker: '8', letter: 't', reminder: false, },
      { marker: '8', letter: 't', reminder: false, },
    ],
    [
      { marker: '4', letter: 'a', reminder: true, },
      { marker: '5', letter: 'n', reminder: true, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
    ],
    [
      { marker: '4', letter: 'a', reminder: true, },
      { marker: '5', letter: 'n', reminder: true, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
    ],
    [
      { marker: '4', letter: 'a', reminder: true, },
      { marker: '5', letter: 'n', reminder: true, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
    ],
    [
      { marker: '4', letter: 'a', reminder: true, },
      { marker: '5', letter: 'n', reminder: true, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
    ],
    [
      { marker: '4', letter: 'a', reminder: true, },
      { marker: '5', letter: 'n', reminder: true, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
    ],
    [
      { marker: '4', letter: 'a', reminder: true, },
      { marker: '5', letter: 'n', reminder: true, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
    ],
    [
      { marker: '4', letter: 'a', reminder: true, },
      { marker: '5', letter: 'n', reminder: true, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
    ],
    [
      { marker: '4', letter: 'a', reminder: true, },
      { marker: '5', letter: 'n', reminder: true, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
    ],
    [
      { marker: '4', letter: 'a', reminder: true, },
      { marker: '5', letter: 'n', reminder: true, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
    ],
    [
      { marker: '4', letter: 'a', reminder: true, },
      { marker: '5', letter: 'n', reminder: true, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
    ],
    [
      { marker: '4', letter: 'a', reminder: true, },
      { marker: '5', letter: 'n', reminder: true, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
    ],
    [
      { marker: '4', letter: 'a', reminder: true, },
      { marker: '5', letter: 'n', reminder: true, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
    ],
    [
      { marker: '4', letter: 'a', reminder: true, },
      { marker: '5', letter: 'n', reminder: true, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
    ],
    [
      { marker: '4', letter: 'a', reminder: true, },
      { marker: '5', letter: 'n', reminder: true, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
      { marker: '8', letter: 'z', reminder: false, },
    ],
  ])
  return (
    <div className="container">
      <Header title={"title"}/>
      <Grid cells={cells}/>
    </div>
  );
}

export default App;
